version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12
      
commands:
  deploy_local:
    description: "run local script"
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run:
          command: |
            chmod +x deploy_local.sh
            ./deploy_local.sh << parameters.env >>


jobs:
  test_node_12:
    executor: node
    working_directory: ~/repo/cats-client
    steps:
      - checkout:
         path: ~/repo
      - restore_cache:
         keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install      
      - deploy_local:
          env: "staging"
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}   
      - run: npm test
   

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test_node_12
      
