version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10
      
commands:
  deploy_local:
    description: "run local script"
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run: sh deploy_local.sh << parameters.env >>


jobs:
  test_node_12:
    executor: node
  working_directory: ~/repo/cats-client
  steps:
    - checkout:
        path: ~/repo
   

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test_node_12
      
