# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    - image: circleci/node:8-browsers
  working_directory: ~/repo/cats-client

version: 2.1

orbs:
  percy: percy/agent@volatile

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout:
          path: ~/repo
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: npm install
          command: sudo npm install -g @percy/agent && sudo npm install --non-interactive
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  run_tests:
    <<: *defaults
    parallelism: 1
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/repo/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: npm build-test && npm test:parallel

workflows:
  test_and_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - run_tests:
          requires:
            - install_dependencies
      - percy/finalize_all:
          requires:
            - run_tests
