version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    working_directory: ~/repo/cats-client
    executor: node
    steps:
      - checkout
        path: ~/repo
      - run: npm start
  test:
    executor: node
    steps:
      - checkout
      - run: npm start
      - run: npm run test
