version: 2.1

exectuors:
  node:
    docker:
     - image: circleci/node:12
      
default_test_steps: &default_test_steps

  working_directory: ~/repo/cats-client
  steps:
    - checkout:
        path: ~/repo
    - run: npm install
    - run: sh deploy_local.sh

jobs:
  test_node_12:
    executor: node
      
    <<: *default_test_steps

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test_node_12
      
