version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.19.0
      
default_test_steps: &default_test_steps

  working_directory: ~/repo/cats-client
   executor: node
  steps:
    - checkout:
        path: ~/repo
    - run: npm install

jobs:
  test_node_12:
    docker:
      - image: circleci/node:12
      
    <<: *default_test_steps

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test_node_12
      
