version: 2.1

default_test_steps: &default_test_steps

  working_directory: ~/repo/cats-client
  steps:
    - checkout:
        path: ~/repo
    - run: npm install

jobs:
  test_node_12:
    docker:
      - image: circleci/node:12
      
working_directory: ~/repo/cats-client
  steps:
    - checkout:
        path: ~/repo
    - run: npm install

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test_node_12
      
